[package]
name = "audio_pipe"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cpal = "0.13.5"
colored = "2.0.0"
anyhow = "1.0"
ringbuf = "0.2.1"
rustfft = "6.0.1"
lazy_static = "1.4.0"