[package]
name = "audio_pipe"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cpal = "0.13.5"
log = "0.4.14"
env_logger = "0.9.0"
colored = "2.0.0"
anyhow = "1.0"